name: Check Code
on:
  - push
  - pull_request
jobs:
  check:
    strategy:
      matrix:
        python:
          - "3.11"
          - "3.12"
          - "3.13"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}
      - run: make dependencies-dev
      - run: make check PYLINTFLAGS=--output-format=github
